{{- if and .Values.server.auth.enabled (not .Values.server.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-auth" (include "helmrepolite.fullname" .) }}
  labels:
    {{- include "helmrepolite.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.server.auth.usernameKey }}: {{ .Values.server.auth.username | quote }}
  {{ .Values.server.auth.passwordKey }}: {{ .Values.server.auth.password | quote }}
{{- end }}
